### ISSUE TITLE
aside 不能弹出的小bug

### ISSUE THREAD

**Issue by fighting20xx** [ddqre12345/ddqre12345.github.io#2]
bug出现的原因
    在 views/index.vue 文件中 。
    第20行  应该改为    return this.$store.state.common.isShowAsideMenu;

    因为你的vuex分模块了，所有要带上模块名  $store.state.common

**Comment by ddqre12345** [comment]
嗯，谢谢，这个bug已经注意到并在最新分支上更改，不过暂未同步到master，还有，你貌似issues提错位置咯
